### ISSUE TITLE
Heroku Database issues

### ISSUE THREAD

**Issue by RachelScodes** [RachelScodes/mymix#2]
#### WHAT YOU ARE TRYING TO SOLVE:

I am trying to initialize and migrate my database on heroku

#### DETAILED DESCRIPTION OF THE BUG/ERROR:

I ran `heroku run rake db:create` and got the following:

```git
Running rake db:create on rachelscodes-mixr... up, run.2321
FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
...
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"d3fn32215ho579", "username"=>"rigccnmcfqtxgr", "password"=>"oopncZ40jelJY_FQcNbytAfJBP", "port"=>5432, "host"=>"ec2-107-21-222-62.compute-1.amazonaws.com"}
```

## WHAT I'VE TRIED

I logged out and back in to make sure it wasn't a login issue. Than I read through [heroku's postgres documentation](https://devcenter.heroku.com/articles/heroku-postgresql). Of note in particular: `You cannot create or modify databases and roles on Heroku Postgres.` The instructions are intense and I'm a little intimidated. 

## QUESTION

Heroku recommends that we export our local database for production... Before I go through those steps, I thought I remembered you guys explicitly telling us NOT to export our local database, to keep them separated. If so, what am I doing wrong? Also heroku says we can't modify permissions. It's not a login issue, so... I'm like... wtf?!

I'll keep on trucking building out my views and links and making sure those all work. WHen one of you has time to take a look at this let a sista know?

**Comment by RachelScodes** [comment]
there has got to be a better way for me to send out a notice. Just @mentions? :/

**Comment by RachelScodes** [comment]
Thanks @DBrodsky90 !!

**Comment by sssyed** [comment]
@RachelScodes mentions totally work. saw it, was at lunch though!

**Comment by RachelScodes** [comment]
@sssyed I'll use mentions next time instead of adding and assigning everyone.
